### ISSUE TITLE
Question on svd_reduction

### ISSUE THREAD

**Issue by Trungmaster5** [moskomule/cca.pytorch#2]
Hello, 
Thank you for great implementation of SVCCA on Pytorch.
In the “svd_reduction" function, you applied V transform on both inputs. Could you explain why you did this ? 
Because I see in the paper’s appendix, the authors wrote  

> X’ = UX 
> Y’ = VY

I’m not familiar with SVD so this question may be naive. But I think it'll be great if you clarify it.

**Comment by moskomule** [comment]
Hi, it's an honor. 
As long as I understand, `U` and `V` are the transposes of left singular vectors of `X` and `Y.`

**Comment by Trungmaster5** [comment]
Thank you for the answer.
