### ISSUE TITLE
Model similarity

### ISSUE THREAD

**Issue by MarioProjects** [moskomule/cca.pytorch#4]
Hi, first of all thanks for your work!

I'm trying to reproduce https://arxiv.org/pdf/1902.07208.pdf. And your repository is perfect :) But I have one question... Figure 3 is can be easily done with your code but Figure 2 computes the simililarity between models... or I udnerstand that. Do you think that is done averaging all layers distances?
Thanks again!

**Comment by moskomule** [comment]
Hi, I'm happy to hear that this work helps others.
In figure 2, they say in the caption "We compute CCA similarity scores between representations learned using pretrained weights and those from random initialization. We do this for the top two layers (or stages for Resnet, Inception) and average the score."

**Comment by MarioProjects** [comment]
Thanks, I'm sure it's helping many people. 
Okay, sorry for losing time, I didn't saw it!
