### ISSUE TITLE
Error: data[0] should be larger than data[1]

### ISSUE THREAD

**Issue by MarioProjects** [moskomule/cca.pytorch#5]
Hi I have tested the following code:

```
from models import *

model = model_selector("resnet34_unet_scratch", 1, in_size=(224, 224))
model = torch.nn.DataParallel(model, device_ids=range(torch.cuda.device_count()))

model2 = model_selector("resnet34_unet_scratch", 1, in_size=(224, 224))
model2 = torch.nn.DataParallel(model2, device_ids=range(torch.cuda.device_count()))

from cca_pytorch.cca import CCAHook
device = "cuda" # or "cpu"

hook1 = CCAHook(model, "module.resnet.layer1.0.conv1", svd_device=device)
hook2 = CCAHook(model2, "module.resnet.layer1.0.conv1", svd_device=device)


model.eval()
model2.eval()

sample = torch.randn(8, 3, 224, 224)
with torch.no_grad():
    model(sample)
    model2(sample)

dist = hook1.distance(hook2)
print(dist)
```

I got error `data[0] should be larger than data[1]`. If I comment his line (https://github.com/moskomule/cca.pytorch/blob/master/cca/cca.py#L52) and rerun I got very small output -> 4.224212979409003e-09. 

Another thing that maybe is not  necesssary is this line -> https://github.com/moskomule/cca.pytorch/blob/master/cca/cca.py#L120 because you overwrite his value in next line, or?

The output for model(sample) is `torch.Size([8, 1, 224, 224])` because I'm working for segmentation. Is not dataparallel fault (I try it) and I don't know your code pretty well more than comment the line :(

**Comment by moskomule** [comment]
Hi, for the first question, `x.size(0) >= x.size(1) and y.size(0) >= y.size(1)` is expected to do meaningful CCA. The error message isn’t good. I think batch size of 8 is too small to compute CCA between layers.
For the second one, you’re correct.

**Comment by MarioProjects** [comment]
But I can't use large batch size :( Is there any way to do it cumulatively so as not to consume as much memory or something similar?

**Comment by moskomule** [comment]
One solution is to set `hook1.distance(hook2, [2, 2])`. This reduces the feature width and hight to be 2.

**Comment by MarioProjects** [comment]
Error line 179 -> `'>' not supported between instances of 'list' and 'int'`.
If I use `dist = hook1.distance(hook2, size=2)` then again past error `data[0] should be larger than data[1]`

**Comment by moskomule** [comment]
Hmm... I will check the problem.

**Comment by moskomule** [comment]
Hi, I will move to https://github.com/moskomule/anatome for the CCA project. Let's discuss it there if you are still interested in this.
