### ISSUE TITLE
Implementation of CCA 

### ISSUE THREAD

**Issue by momih** [moskomule/cca.pytorch#7]
I was having a look at the `_svd_cca` function and I'm quite confused by how you perform CCA. Other implementations I've seen use the covariance matrices between X and Y but the repo uses SVD on X and Y themselves. I'm not that familiar with CCA, can you explain (or provide a link) how the math behind the two approaches is equivalent? Thanks!

**Comment by maduc7** [comment]
Hi, did you find any prove of the equivalence? Thanks

**Comment by moskomule** [comment]
Hi, check Press 2011 "Canonical Correlation Clarified by Singular Value Decomposition".
I will drop the support of this library, so please check https://github.com/moskomule/anatome in the future.
