### ISSUE TITLE
Question about _conv2d_reshape

### ISSUE THREAD

**Issue by ziqi-zhang** [moskomule/cca.pytorch#8]
Hi, thanks for sharing the awesome code!

Because of the limited NVIDIA driver version, I can only try this repo instead of anatome. I have a question about the permute in the _conv2d_reshape [here](https://github.com/moskomule/cca.pytorch/blob/c42c41583413f7f47597d6ba4cb983c74056356e/cca/cca.py#L182). I think the permuted shape should be (h* w, b, c) and cca_function computes every (b,c). Why you don't keep the shape to be (b,c,h* w) and compute the cca of every (c, h* w)? 

And if I want to compute the per-sample similarity between models I think I should not use permute and compute the cca of (c, h* w)?

Thanks,

**Comment by moskomule** [comment]
Two networks evolved from different initial states are expected to have similar representations at each pixel (i.e., `h, w`), but the channel-wise orders can be different. So, CCA-based methods compare `BxC`matrices.

**Comment by brando90** [comment]
this library is not supported anymore. Check this one https://github.com/moskomule/anatome @ziqi-zhang
